import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import type { Metadata } from "next";
import NavBar from "@/components/NavBar";
import AddButton from "@/components/AddButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <link rel="manifest" href="/manifest.json" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
          />
        </head>
        <body>
          <NavBar />
          <div className="px-4 pt-12 h-screen md:flex md:justify-center">
            <div className="md:p-24">{children}</div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
